# Generated by Django 4.1.4 on 2023-01-10 22:14

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('happy_new_year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2023, 1, 10, 22, 14, 16, 877958, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
            ],
        ),
    ]
